[2024-05-15T20:07:31.246+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: evalmlops_models.train_model_task scheduled__2024-05-14T00:00:00+00:00 [queued]>
[2024-05-15T20:07:31.270+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: evalmlops_models.train_model_task scheduled__2024-05-14T00:00:00+00:00 [queued]>
[2024-05-15T20:07:31.270+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-05-15T20:07:31.311+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): train_model_task> on 2024-05-14 00:00:00+00:00
[2024-05-15T20:07:31.334+0000] {standard_task_runner.py:60} INFO - Started process 336 to run task
[2024-05-15T20:07:31.367+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'evalmlops_models', 'train_model_task', 'scheduled__2024-05-14T00:00:00+00:00', '--job-id', '79', '--raw', '--subdir', 'DAGS_FOLDER/predict_data.py', '--cfg-path', '/tmp/tmp4ye1vrlt']
[2024-05-15T20:07:31.369+0000] {standard_task_runner.py:88} INFO - Job 79: Subtask train_model_task
[2024-05-15T20:07:31.541+0000] {task_command.py:423} INFO - Running <TaskInstance: evalmlops_models.train_model_task scheduled__2024-05-14T00:00:00+00:00 [running]> on host 0f2797502ce2
[2024-05-15T20:07:31.833+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='evalmlops_models' AIRFLOW_CTX_TASK_ID='train_model_task' AIRFLOW_CTX_EXECUTION_DATE='2024-05-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-14T00:00:00+00:00'
[2024-05-15T20:07:32.027+0000] {logging_mixin.py:188} INFO -    etiquette_dpe  ...  type_energie_n_1
0              0  ...                 4
1              0  ...                 4
2              0  ...                 4
3              0  ...                 4
4              0  ...                 4

[5 rows x 5 columns]
[2024-05-15T20:07:32.258+0000] {logging_mixin.py:188} WARNING - 2024/05/15 20:07:32 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2024-05-15T20:07:32.334+0000] {logging_mixin.py:188} INFO - training on 200 samples
[2024-05-15T20:07:32.387+0000] {logging_mixin.py:188} WARNING - 2024/05/15 20:07:32 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "/home/***/.local/lib/python3.8/site-packages/mlflow/types/utils.py:394: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
[2024-05-15T20:07:37.410+0000] {__init__.py:531} WARNING - Matplotlib created a temporary cache directory at /tmp/matplotlib-i5c0v7xy because the default path (/home/airflow/.cache/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
[2024-05-15T20:07:38.125+0000] {font_manager.py:1547} INFO - generated new fontManager
[2024-05-15T20:07:39.179+0000] {logging_mixin.py:188} WARNING - 2024/05/15 20:07:39 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "/home/***/.local/lib/python3.8/site-packages/mlflow/types/utils.py:394: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
[2024-05-15T20:07:47.932+0000] {logging_mixin.py:188} WARNING - 2024/05/15 20:07:47 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "/home/***/.local/lib/python3.8/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils."
[2024-05-15T20:07:52.205+0000] {logging_mixin.py:188} WARNING - 2024/05/15 20:07:52 INFO mlflow.sklearn.utils: Logging the 5 best runs, no runs will be omitted.
[2024-05-15T20:07:52.470+0000] {logging_mixin.py:188} WARNING - 2024/05/15 20:07:52 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "/home/***/.local/lib/python3.8/site-packages/mlflow/types/utils.py:394: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
[2024-05-15T20:07:52.598+0000] {logging_mixin.py:188} WARNING - 2024/05/15 20:07:52 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "/home/***/.local/lib/python3.8/site-packages/mlflow/types/utils.py:394: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
[2024-05-15T20:07:52.613+0000] {logging_mixin.py:188} INFO - ---------------------------------------- Best model
[2024-05-15T20:07:52.613+0000] {logging_mixin.py:188} INFO - 	parameters: {'max_depth': 9, 'min_samples_leaf': 4, 'n_estimators': 60}
[2024-05-15T20:07:52.614+0000] {logging_mixin.py:188} INFO - 	cross-validation score: 0.5926611162503854
[2024-05-15T20:07:52.618+0000] {logging_mixin.py:188} INFO - 	model: RandomForestClassifier(max_depth=9, min_samples_leaf=4, n_estimators=60)
[2024-05-15T20:07:52.618+0000] {logging_mixin.py:188} INFO - ---------------------------------------- performance
[2024-05-15T20:07:52.619+0000] {logging_mixin.py:188} INFO - 	precision_score: 0.53
[2024-05-15T20:07:52.620+0000] {logging_mixin.py:188} INFO - 	recall_score: 0.53
[2024-05-15T20:07:52.620+0000] {logging_mixin.py:188} INFO - 	median(probabilities): 0.55
[2024-05-15T20:07:52.621+0000] {logging_mixin.py:188} INFO - 	std(probabilities): 0.07
[2024-05-15T20:07:52.807+0000] {logging_mixin.py:188} WARNING - 2024/05/15 20:07:52 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: dpe_challenger, version 4
[2024-05-15T20:07:52.808+0000] {warnings.py:109} WARNING - /opt/***/dags/predict_data.py:216: FutureWarning: ``mlflow.tracking.client.MlflowClient.transition_model_version_stage`` is deprecated since 2.9.0. Model registry stages will be removed in a future major release. To learn more about the deprecation of model registry stages, see our migration guide here: https://mlflow.org/docs/2.12.2/model-registry.html#migrating-from-stages
  client.transition_model_version_stage(

[2024-05-15T20:07:52.840+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-05-15T20:07:52.857+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=evalmlops_models, task_id=train_model_task, execution_date=20240514T000000, start_date=20240515T200731, end_date=20240515T200752
[2024-05-15T20:07:52.941+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-05-15T20:07:52.980+0000] {taskinstance.py:3312} INFO - 1 downstream tasks scheduled from follow-on schedule check
